### ISSUE TITLE
Pass flags when installing a specific package

### ISSUE THREAD

**Issue by unindented** [superlumic/ansible-role-homebrew#2]
For example, I want to install MacVim with the `--with-override-system-vim` flag. Currently I have something like this:

```
- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - macvim
    - tmux
```

Thanks @roderik!
